apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-external-secrets-rds-sa
  namespace: openshift-dbaas-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    eks.amazonaws.com/role-arn: arn:aws:iam::301372634383:role/axelrosa-RosaRdsClusterSecrets
